name: mhcflurry-minimal-2.7
dependencies:
- certifi=2016.2.28=py27_0
- funcsigs=1.0.2=py27_0
- libprotobuf=3.2.0=0
- mkl=2017.0.3=0
- mock=2.0.0=py27_0
- numpy=1.12.1=py27_0
- openssl=1.0.2l=0
- pbr=1.10.0=py27_0
- protobuf=3.2.0=py27_0
- readline=6.2=2
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tensorflow=1.1.0=np112py27_0
- tk=8.5.18=0
- werkzeug=0.12.2=py27_0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - alabaster==0.7.10
  - appdirs==1.4.3
  - babel==2.5.1
  - biopython==1.70
  - chardet==3.0.4
  - datacache==0.4.20
  - docutils==0.14
  - futures==3.2.0
  - gtfparse==0.0.6
  - idna==2.6
  - imagesize==0.7.1
  - jinja2==2.10
  - keras==2.1.2
  - markupsafe==1.0
  - memoized-property==1.0.3
  - mhcnames==0.3.11
  - mhctools==1.6.8
  - numpydoc==0.7.0
  - pandas==0.21.1
  - progressbar33==2.4
  - pydot==1.2.3
  - pyensembl==1.1.0
  - pygments==2.2.0
  - pypandoc==1.4
  - pyparsing==2.2.0
  - python-dateutil==2.6.1
  - pytz==2017.3
  - pyvcf==0.6.8
  - pyyaml==3.12
  - requests==2.18.4
  - scikit-learn==0.19.1
  - scipy==1.0.0
  - sercol==0.1.0
  - serializable==0.1.1
  - simplejson==3.13.2
  - snowballstemmer==1.2.1
  - sphinx==1.6.5
  - sphinx-rtd-theme==0.2.4
  - sphinxcontrib-autoprogram==0.1.3
  - sphinxcontrib-autorun2==0.1.post20140415
  - sphinxcontrib-programoutput==0.11
  - sphinxcontrib-websupport==1.0.1
  - tinytimer==0.0.0
  - typechecks==0.0.2
  - typing==3.6.2
  - urllib3==1.22
  - varcode==0.5.15
